# Star Wars Data Analysis

Este notebook realiza uma análise exploratória dos dados extraídos da SWAPI
(Star Wars API) e armazenados em PostgreSQL.

Objetivos da análise:

- Identificar o personagem que apareceu em mais filmes
- Encontrar os planetas mais quentes do uniserso de Star Wars
- Identificar as naves espaciais mais rápidas
- Identificar a arma mais poderosa no universo Star Wars

## Importar bibliotecas

In [20]:
import psycopg2
import pandas as pd
import os
from dotenv import load_dotenv

In [21]:
load_dotenv()

True

## Conectar ao banco

In [23]:
conn = psycopg2.connect(
    host=os.getenv("DB_HOST"),
    database=os.getenv("DB_NAME"),
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"), 
    port=os.getenv("DB_PORT")
)

## Análise exploratória

In [24]:
query = "SELECT * FROM people LIMIT 10"

df_people = pd.read_sql(query, conn)
df_people

/tmp/ipykernel_72074/1248009344.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_people = pd.read_sql(query, conn)

,id,name,height,mass,birth_year,gender,url,films_count,created_at
0,1,Luke Skywalker,172,77.0,19BBY,male,https://swapi.dev/api/people/1/,4,2026-03-07 23:12:53.327853
1,2,C-3PO,167,75.0,112BBY,n/a,https://swapi.dev/api/people/2/,6,2026-03-07 23:12:53.327853
2,3,R2-D2,96,32.0,33BBY,n/a,https://swapi.dev/api/people/3/,6,2026-03-07 23:12:53.327853
3,4,Darth Vader,202,136.0,41.9BBY,male,https://swapi.dev/api/people/4/,4,2026-03-07 23:12:53.327853
4,5,Leia Organa,150,49.0,19BBY,female,https://swapi.dev/api/people/5/,4,2026-03-07 23:12:53.327853
5,6,Owen Lars,178,120.0,52BBY,male,https://swapi.dev/api/people/6/,3,2026-03-07 23:12:53.327853
6,7,Beru Whitesun lars,165,75.0,47BBY,female,https://swapi.dev/api/people/7/,3,2026-03-07 23:12:53.327853
7,8,R5-D4,97,32.0,unknown,n/a,https://swapi.dev/api/people/8/,1,2026-03-07 23:12:53.327853
8,9,Biggs Darklighter,183,84.0,24BBY,male,https://swapi.dev/api/people/9/,1,2026-03-07 23:12:53.327853
9,10,Obi-Wan Kenobi,182,77.0,57BBY,male,https://swapi.dev/api/people/10/,6,2026-03-07 23:12:53.327853

### Qual é o personagem que apareceu em mais filmes de Star Wars?

In [25]:
query = """
SELECT name, films_count
FROM people
ORDER BY films_count DESC
LIMIT 5
"""

pd.read_sql(query, conn)

/tmp/ipykernel_72074/2031989754.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

             name  films_count
0  Obi-Wan Kenobi            6
1           R2-D2            6
2           C-3PO            6
3            Yoda            5
4       Palpatine            5

De acordo com os dados obtidos pela API SWAPI, os personagens Obi-Wan Kenobi, R2-D2 e C-3PO são os que mais aparecem nos filmes da saga Star Wars dentro do conjunto analisado, cada um com participação em 6 filmes. Essa frequência elevada indica que esses personagens possuem um papel central na narrativa da franquia, estando presentes em diferentes momentos da história e acompanhando eventos importantes do desenvolvimento da saga. Por esse motivo, eles aparecem como os personagens com maior número de participações no resultado da análise.

**Importante:** Embora algumas fontes indiquem que C-3PO aparece em cerca de 10 filmes da franquia Star Wars, os dados obtidos pela API SWAPI apontam 6 participações. Isso ocorre porque a API considera apenas os filmes listados em seu conjunto de dados principal, enquanto outras fontes incluem participações adicionais em outros filmes da franquia, como produções derivadas, animações ou aparições especiais. Dessa forma, a diferença está relacionada ao escopo dos dados utilizados na análise.

In [32]:
query_filmes = """
SELECT 
    episode_id AS episodio, 
    title AS titulo, 
    release_date AS lancamento
FROM films
ORDER BY episode_id;
"""

pd.read_sql(query_filmes, conn)

/tmp/ipykernel_72074/741439641.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_filmes, conn)

   episodio                   titulo  lancamento
0         1       The Phantom Menace  1999-05-19
1         2     Attack of the Clones  2002-05-16
2         3      Revenge of the Sith  2005-05-19
3         4               A New Hope  1977-05-25
4         5  The Empire Strikes Back  1980-05-17
5         6       Return of the Jedi  1983-05-25

Através da tabela de filmes é possível saber a quantidade de filmes que foram extraidos da API e quais são esses filmes.

### Quais são os planetas mais quentes do universo de Star Wars?

In [28]:
query_planetas_quentes = """
SELECT 
    name, 
    climate, 
    terrain
FROM planets
WHERE climate LIKE '%arid%' 
   OR climate LIKE '%hot%' 
   OR climate LIKE '%tropical%'
ORDER BY climate ASC;
"""

pd.read_sql(query_planetas_quentes, conn)

/tmp/ipykernel_72074/1848117237.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query_planetas_quentes, conn)

,name,climate,terrain
0,Trandosha,arid,"mountains, seas, grasslands, deserts"
1,Tatooine,arid,desert
2,Socorro,arid,"deserts, mountains"
3,Iktotch,"arid, rocky, windy",rocky
4,Kalee,"arid, temperate, tropical","rainforests, cliffs, canyons, seas"
5,Malastare,"arid, temperate, tropical","swamps, deserts, jungles, mountains"
6,Mustafar,hot,"volcanoes, lava rivers, mountains, caves"
7,Saleucami,hot,"caves, desert, mountains, volcanoes"
8,Rodia,hot,"jungles, oceans, urban, swamps"
9,Felucia,"hot, humid",fungus forests
10,Geonosis,"temperate, arid","rock, desert, mountain, barren"
11,Ryloth,"temperate, arid, subartic","mountains, valleys, deserts, tundra"
12,Utapau,"temperate, arid, windy","scrublands, savanna, canyons, sinkholes"
13,Yavin IV,"temperate, tropical","jungle, rainforests"
14,Kashyyyk,tropical,"jungle, forests, lakes, rivers"
15,Glee Anselm,"tropical, temperate","lakes, islands, swamps, seas"

### Quais são as naves espaciais mais rápida do universo de Star Wars?

In [29]:
query = """
SELECT name, max_atmosphering_speed
FROM starships
WHERE max_atmosphering_speed IS NOT NULL
ORDER BY max_atmosphering_speed DESC
LIMIT 5
"""

pd.read_sql(query, conn)

/tmp/ipykernel_72074/2748361124.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, conn)

                       name  max_atmosphering_speed
0       H-type Nubian yacht                  8000.0
1  Theta-class T-2c shuttle                  2000.0
2   J-type diplomatic barge                  2000.0
3              Solar Sailer                  1600.0
4          Jedi Interceptor                  1500.0